In [1]:
!pip install pandas
!pip install openpyxl

In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
df = pd.read_excel(r'C:\Users\user\Desktop\RNN\good_sentence(나머지).xlsx')
df.head()

Sentence  label
0                                  붓다가 보면 어떤 생각을 하실까      0
1                         늘 니글보면서 느끼는거지만 이란을굉장히좋아하는듯      0
2  게이클럽만 공개한다면 차별이다. 근데 게이클럽도 공개했다면 뭐가 문젠가? 이런 기사...      0
3                                              함 박아줘      0
4  의료협회가 잘하고 있는거지... 아직도 입국금지 안하고 교민들 유학생들 받는건 좀 ...      0

In [4]:
sentences = df['Sentence'].tolist()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)
print(tokenizer.word_index)

단어 집합의 크기 : 40559
{'왜': 1, '진짜': 2, '너무': 3, '다': 4, '좀': 5, '더': 6, 'ㅋㅋ': 7, '그냥': 8, '잘': 9, '근데': 10, 'ㅋㅋㅋ': 11, '이': 12, '난': 13, '정말': 14, '참': 15, '이제': 16, 'ㅋ': 17, '무슨': 18, '또': 19, '그': 20, '많이': 21, 'ㅠㅠ': 22, '저': 23, '뭐': 24, '아니고': 25, '안': 26, '이렇게': 27, '솔직히': 28, '사람': 29, '보고': 30, '이런': 31, '하고': 32, '드라마': 33, '연기': 34, '역시': 35, '그래도': 36, 'ㅋㅋㅋㅋ': 37, '얼마나': 38, '내가': 39, '제발': 40, '수': 41, '하는': 42, '넘': 43, '요즘': 44, '와': 45, '아': 46, '누가': 47, '그리고': 48, '지금': 49, '꼭': 50, '아니': 51, '다시': 52, '그렇게': 53, 'ㅠ': 54, '보면': 55, '이게': 56, '아님': 57, '제일': 58, '다른': 59, '나도': 60, '한': 61, '그만': 62, '어떻게': 63, '나': 64, '돈': 65, 'ㅎㅎ': 66, '기사': 67, '같이': 68, '같은데': 69, '같은': 70, '사람이': 71, '뭔': 72, '화이팅': 73, '좋은': 74, '저렇게': 75, '연예인': 76, '하나': 77, 'ㅉㅉ': 78, '것': 79, '거': 80, '계속': 81, '못': 82, '오늘': 83, '이미': 84, '이거': 85, '다들': 86, '뭘': 87, '존나': 88, '없다': 89, '항상': 90, '그럼': 91, '둘이': 92, '아니라': 93, '해라': 94, '아닌데': 95, '얼굴': 96, 'ㅋㅋㅋㅋㅋ': 97, '좋겠다': 98, '완전': 99, '응원합니

In [5]:
sequences = list()
for line in sentences:
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[: i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수 : %d' % len(sequences))
print(sequences)

학습에 사용할 샘플의 개수 : 62755
[[7115, 55], [7115, 55, 189], [7115, 55, 189, 897], [7115, 55, 189, 897, 7116], [208, 7117], [208, 7117, 7118], [208, 7117, 7118, 7119], [7120, 7121], [7120, 7121, 3637], [7120, 7121, 3637, 10], [7120, 7121, 3637, 10, 7122], [7120, 7121, 3637, 10, 7122, 7123], [7120, 7121, 3637, 10, 7122, 7123, 135], [7120, 7121, 3637, 10, 7122, 7123, 135, 7124], [7120, 7121, 3637, 10, 7122, 7123, 135, 7124, 31], [7120, 7121, 3637, 10, 7122, 7123, 135, 7124, 31, 67], [7120, 7121, 3637, 10, 7122, 7123, 135, 7124, 31, 67, 7125], [162, 7126], [7127, 371], [7127, 371, 2316], [7127, 371, 2316, 102], [7127, 371, 2316, 102, 7128], [7127, 371, 2316, 102, 7128, 441], [7127, 371, 2316, 102, 7128, 441, 7129], [7127, 371, 2316, 102, 7128, 441, 7129, 7130], [7127, 371, 2316, 102, 7128, 441, 7129, 7130, 3638], [7127, 371, 2316, 102, 7128, 441, 7129, 7130, 3638, 5], [7127, 371, 2316, 102, 7128, 441, 7129, 7130, 3638, 5, 1059], [7127, 371, 2316, 102, 7128, 441, 7129, 7130, 3638, 5, 1059, 7131], 

In [6]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

샘플의 최대 길이 : 39
[[    0     0     0 ...     0  7115    55]
 [    0     0     0 ...  7115    55   189]
 [    0     0     0 ...    55   189   897]
 ...
 [    0     0     0 ...     0  1985 40557]
 [    0     0     0 ...  1985 40557   107]
 [    0     0     0 ... 40557   107 40558]]


In [7]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

print(sequences.shape)

(62755, 39)


In [8]:
print(X)

[[    0     0     0 ...     0     0  7115]
 [    0     0     0 ...     0  7115    55]
 [    0     0     0 ...  7115    55   189]
 ...
 [    0     0     0 ...     0     0  1985]
 [    0     0     0 ...     0  1985 40557]
 [    0     0     0 ...  1985 40557   107]]


In [9]:
print(y)

[   55   189   897 ... 40557   107 40558]


In [10]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### 2) 모델 설계하기
RNN 모델에 데이터를 훈련시키기

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [12]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1962/1962 - 41s - loss: 10.5501 - accuracy: 0.0040 - 41s/epoch - 21ms/step
Epoch 2/200
1962/1962 - 40s - loss: 9.9321 - accuracy: 0.0047 - 40s/epoch - 20ms/step
Epoch 3/200
1962/1962 - 39s - loss: 9.4457 - accuracy: 0.0059 - 39s/epoch - 20ms/step
Epoch 4/200
1962/1962 - 40s - loss: 9.0241 - accuracy: 0.0070 - 40s/epoch - 21ms/step
Epoch 5/200
1962/1962 - 38s - loss: 8.6174 - accuracy: 0.0090 - 38s/epoch - 20ms/step
Epoch 6/200
1962/1962 - 39s - loss: 8.2269 - accuracy: 0.0144 - 39s/epoch - 20ms/step
Epoch 7/200
1962/1962 - 38s - loss: 7.8618 - accuracy: 0.0221 - 38s/epoch - 19ms/step
Epoch 8/200
1962/1962 - 38s - loss: 7.5165 - accuracy: 0.0341 - 38s/epoch - 19ms/step
Epoch 9/200
1962/1962 - 38s - loss: 7.1896 - accuracy: 0.0507 - 38s/epoch - 20ms/step
Epoch 10/200
1962/1962 - 39s - loss: 6.8815 - accuracy: 0.0694 - 39s/epoch - 20ms/step
Epoch 11/200
1962/1962 - 42s - loss: 6.5912 - accuracy: 0.0934 - 42s/epoch - 21ms/step
Epoch 12/200
1962/1962 - 42s - loss: 6.3133 - accur

In [16]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence  = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items():
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + dPcmr eksdjfmf guswo eksdjfh qusrud
        current_word = current_word + ' ' + word
        
        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word
    
    sentence = init_word + sentence
    return sentence

In [20]:
print(sentence_generation(model, tokenizer, '구라', 10))

구라 사람은 나가는 노잼 왜그래요 무혐의 뭐라 하차 ㅋㅋ 봐주자 나오는
