In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
df = pd.read_excel(r'C:/Users/GJAISCHOOL/Desktop/X_filter/Algorithm/dataset/good_sentence.xlsx')
df.head()

Sentence  label
0     집에 롱 패딩만 세 개다. 10년 더 입어야지 ㅋㅋ      0
1                      세탁이라고 봐도 된다      0
2  은행에 대출 상담 받으러 가보면 직업의 귀천 바로 알려줌      0
3                            ㅋㅋㅋㅋㅋ      0
4                            ㄹㅇㅋㅋㅋ      0

In [3]:
sentences = df['Sentence'].tolist()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)
print(tokenizer.word_index)

단어 집합의 크기 : 545
{'다': 1, '그냥': 2, 'ㅋㅋ': 3, '이게': 4, '난': 5, '누가': 6, '나': 7, '아': 8, 'ㄹㅇ': 9, '바로': 10, '아예': 11, '아이디': 12, '비번': 13, '파일에': 14, '등등': 15, 'ㅋㅋㅋ': 16, '말이': 17, '여기': 18, '뭐': 19, '너무': 20, '오이': 21, '강력계': 22, '니가': 23, '그': 24, 'ㅋㅋㅋㅋ': 25, '집에': 26, '롱': 27, '패딩만': 28, '세': 29, '개다': 30, '10년': 31, '더': 32, '입어야지': 33, '세탁이라고': 34, '봐도': 35, '된다': 36, '은행에': 37, '대출': 38, '상담': 39, '받으러': 40, '가보면': 41, '직업의': 42, '귀천': 43, '알려줌': 44, 'ㅋㅋㅋㅋㅋ': 45, 'ㄹㅇㅋㅋㅋ': 46, '우리지역군데': 47, '금태섭': 48, '뽑으면': 49, '안되지': 50, '그래도': 51, '자한당': 52, '뻡아야겠지': 53, '백정주제에': 54, '라고하는걸': 55, '비하라고': 56, '느낀다면': 57, '본인조차': 58, '직업에': 59, '자부심이': 60, '없는건데': 61, '백인': 62, '탓이랑께': 63, '마감시간': 64, '다돼서': 65, '떨이하는': 66, '고기': 67, '사먹으면': 68, '식중독': 69, '518퍼네아': 70, '오래': 71, '된': 72, '것도': 73, '새': 74, '거처럼': 75, '둔갑해서': 76, '다음날': 77, '팔테니': 78, '떨이라는': 79, '개념이': 80, '없을라나': 81, '열사발': 82, '들이켜도': 83, '아깝지': 84, '않음': 85, '으따': 86, '옷': 87, '이딴건': 88, '필요': 89, '없당깨': 90, '현금으로': 91, '달랑깨': 92

In [4]:
sequences = list()
for line in sentences:
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[: i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수 : %d' % len(sequences))
print(sequences)

학습에 사용할 샘플의 개수 : 481
[[26, 27], [26, 27, 28], [26, 27, 28, 29], [26, 27, 28, 29, 30], [26, 27, 28, 29, 30, 31], [26, 27, 28, 29, 30, 31, 32], [26, 27, 28, 29, 30, 31, 32, 33], [26, 27, 28, 29, 30, 31, 32, 33, 3], [34, 35], [34, 35, 36], [37, 38], [37, 38, 39], [37, 38, 39, 40], [37, 38, 39, 40, 41], [37, 38, 39, 40, 41, 42], [37, 38, 39, 40, 41, 42, 43], [37, 38, 39, 40, 41, 42, 43, 10], [37, 38, 39, 40, 41, 42, 43, 10, 44], [47, 48], [47, 48, 49], [47, 48, 49, 50], [47, 48, 49, 50, 51], [47, 48, 49, 50, 51, 52], [47, 48, 49, 50, 51, 52, 53], [54, 55], [54, 55, 56], [54, 55, 56, 57], [54, 55, 56, 57, 58], [54, 55, 56, 57, 58, 59], [54, 55, 56, 57, 58, 59, 60], [54, 55, 56, 57, 58, 59, 60, 61], [4, 1], [4, 1, 62], [4, 1, 62, 63], [64, 65], [64, 65, 66], [64, 65, 66, 67], [64, 65, 66, 67, 68], [64, 65, 66, 67, 68, 69], [64, 65, 66, 67, 68, 69, 70], [64, 65, 66, 67, 68, 69, 70, 71], [64, 65, 66, 67, 68, 69, 70, 71, 72], [64, 65, 66, 67, 68, 69, 70, 71, 72, 73], [64, 65, 66, 67, 68, 69, 70

In [5]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

샘플의 최대 길이 : 30
[[  0   0   0 ...   0  26  27]
 [  0   0   0 ...  26  27  28]
 [  0   0   0 ...  27  28  29]
 ...
 [  0   0   0 ... 540 541 542]
 [  0   0   0 ... 541 542 543]
 [  0   0   0 ... 542 543 544]]


In [6]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

print(sequences.shape)

(481, 30)


In [7]:
print(X)

[[  0   0   0 ...   0   0  26]
 [  0   0   0 ...   0  26  27]
 [  0   0   0 ...  26  27  28]
 ...
 [  0   0   0 ...   0 540 541]
 [  0   0   0 ... 540 541 542]
 [  0   0   0 ... 541 542 543]]


In [8]:
print(y)

[ 27  28  29  30  31  32  33   3  35  36  38  39  40  41  42  43  10  44
  48  49  50  51  52  53  55  56  57  58  59  60  61   1  62  63  65  66
  67  68  69  70  71  72  73  74  75  76  77  78  79  80  11  81  83  84
  85  87  88  89  90  91  92  93  94  12  13   1  95  96  97  14  98  12
  13  99  15   1 100 101 102  14 103 104 105 106 107 108 109 110 112 113
 114 115 116 118 119 122 123 124 126 128 130 132 133 134 136 138 139 140
 141 142 143 144 145 146 147 148 149 150 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 168 170 171 172 173 174 175 176 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 194 195 197 199 201 202
 203   6 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
  16 220 221 222 223 224 225 226 227 228 230 231 233 234 235 236 237 238
 239 240 241 242 243 244 245 246 247 248 249 250 251  17 252 253 254 255
 256 257 258 259 260 262 263 264 265 266 267 268  16 270  18 273 274 275
  18 276 277   2 278 279 281 282 284 285 286 287 28

In [9]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### 2) 모델 설계하기
RNN 모델에 데이터를 훈련시키기

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [12]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200


InternalError: Graph execution error:

Detected at node 'sequential_1/simple_rnn_1/while/simple_rnn_cell_1/MatMul_1' defined at (most recent call last):
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\traitlets\config\application.py", line 1053, in launch_instance
      app.start()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelapp.py", line 737, in start
      self.io_loop.start()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 524, in dispatch_queue
      await self.process_one()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 513, in process_one
      await dispatch(*args)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 418, in dispatch_shell
      await result
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 758, in execute_request
      reply_content = await reply_content
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\ipkernel.py", line 426, in do_execute
      res = shell.run_cell(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
      result = self._run_cell(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
      result = runner(coro)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\GJAISCHOOL\AppData\Local\Temp\ipykernel_9664\827228583.py", line 1, in <module>
      model.fit(X, y, epochs=200, verbose=2)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 889, in train_step
      y_pred = self(x, training=True)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\sequential.py", line 374, in call
      return super(Sequential, self).call(inputs, training=training, mask=mask)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\functional.py", line 458, in call
      return self._run_internal_graph(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 515, in __call__
      return super(RNN, self).__call__(inputs, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\simple_rnn.py", line 391, in call
      return super(SimpleRNN, self).call(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 652, in call
      last_output, outputs, states = backend.rnn(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 4776, in rnn
      final_outputs = tf.compat.v1.while_loop(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 4759, in _step
      output, new_states = step_function(current_input,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 648, in step
      output, new_states = cell_call_fn(inputs, states, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\simple_rnn.py", line 194, in call
      output = h + backend.dot(prev_output, self.recurrent_kernel)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 2223, in dot
      out = tf.matmul(x, y)
Node: 'sequential_1/simple_rnn_1/while/simple_rnn_cell_1/MatMul_1'
Attempting to perform BLAS operation using StreamExecutor without BLAS support
	 [[{{node sequential_1/simple_rnn_1/while/simple_rnn_cell_1/MatMul_1}}]] [Op:__inference_train_function_3023]

In [18]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence  = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items():
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + dPcmr eksdjfmf guswo eksdjfh qusrud
        current_word = current_word + ' ' + word
        
        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word
    
    sentence = init_word + sentence
    return sentence

In [ ]:
print(sentence_generation(model, tokenizer, '사랑해', 10))