# RNN

In [1]:
!pip show numpy pandas tensorflow # 1.24.4 # 2.0.3 # 2.9.3

Name: numpy
Version: 1.24.4
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: c:\users\gjaischool\.conda\envs\nv38\lib\site-packages
Requires: 
Required-by: accelerate, blis, contourpy, h5py, Keras-Preprocessing, kiwipiepy, konlpy, Korpora, matplotlib, opt-einsum, pandas, pecab, pyarrow, scikit-learn, scipy, soynlp, spacy, tensorboard, tensorflow, tensorflow-gpu, thinc, transformers, wordcloud
---
Name: pandas
Version: 2.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: 
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License
        
        Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
        All rights reserved.
        
        Copyright (c) 2011-2023, Open source contributors.
        
        Redistribution a

In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
df = pd.read_csv(r'C:\Users\GJAISCHOOL\Desktop\X_filter\Algorithm\dataset\good_sentence.csv')
df.head()

sentence  label
0   질병은 입을 좇아 들어가고 화근은 입을 좇아 나온다… 태평어람      0
1        행복이란 타인을 행복하게 해주려는 노력의 부산물이다.      0
2          지혜는 듣는 데서 오고 후회는 말하는 데서 온다.      0
3  인간은 의욕하는 것, 그리고 창조하는 것에 의해서만이 행복하다.      0
4           말을 많이 하는 것과 말을 잘하는 것은 다르다.      0

In [8]:
sentences = df['sentence'].tolist()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)
print(tokenizer.word_index)

단어 집합의 크기 : 2330
{'것이다': 1, '없다': 2, '수': 3, '있는': 4, '것은': 5, '있다': 6, '사람은': 7, '한': 8, '것이': 9, '것을': 10, '가장': 11, '말라': 12, '좋은': 13, '않는다': 14, '그': 15, '한다': 16, '자는': 17, '사랑은': 18, '그라시안': 19, '모든': 20, '더': 21, '없는': 22, '하는': 23, '일을': 24, '않는': 25, '–': 26, '아니라': 27, '인간은': 28, '할': 29, '인생은': 30, '나폴레옹': 31, '일이다': 32, '많은': 33, '아니다': 34, '말고': 35, '하고': 36, '일이': 37, '된다': 38, '사람을': 39, '프랭클린': 40, '괴테': 41, '하나의': 42, '그것을': 43, '두': 44, '번': 45, '큰': 46, '나의': 47, '않으면': 48, '마음의': 49, '속담': 50, '것도': 51, '그리고': 52, '바로': 53, '이룰': 54, '결코': 55, '탈무드': 56, '인생을': 57, '낫다': 58, '니체': 59, '에머슨': 60, '못한다': 61, '사람이': 62, '것에': 63, '자기': 64, '진정한': 65, '그러면': 66, '사는': 67, '셰익스피어': 68, '나는': 69, '그것은': 70, '사랑하는': 71, '않은': 72, '곧': 73, '그것이': 74, '자기가': 75, '앤드류': 76, '그러나': 77, '없이': 78, '모른다': 79, '위대한': 80, '하지': 81, '영국속담': 82, '자의': 83, '기회가': 84, '사랑을': 85, '말하는': 86, '것': 87, '파스칼': 88, '하라': 89, '노자': 90, '대한': 91, '제일': 92, '법이다': 93, '죽음을': 94, '다시': 95, '사랑의

In [9]:
sequences = list()
for line in sentences:
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[: i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수 : %d' % len(sequences))
print(sequences)

학습에 사용할 샘플의 개수 : 3892
[[807, 330], [807, 330, 331], [807, 330, 331, 808], [807, 330, 331, 808, 809], [807, 330, 331, 808, 809, 330], [807, 330, 331, 808, 809, 330, 331], [807, 330, 331, 808, 809, 330, 331, 810], [807, 330, 331, 808, 809, 330, 331, 810, 811], [332, 333], [332, 333, 812], [332, 333, 812, 813], [332, 333, 812, 813, 814], [332, 333, 812, 813, 814, 815], [334, 335], [334, 335, 336], [334, 335, 336, 816], [334, 335, 336, 816, 817], [334, 335, 336, 816, 817, 86], [334, 335, 336, 816, 817, 86, 336], [334, 335, 336, 816, 817, 86, 336, 818], [28, 121], [28, 121, 87], [28, 121, 87, 52], [28, 121, 87, 52, 122], [28, 121, 87, 52, 122, 63], [28, 121, 87, 52, 122, 63, 123], [28, 121, 87, 52, 122, 63, 123, 124], [125, 126], [125, 126, 23], [125, 126, 23, 212], [125, 126, 23, 212, 125], [125, 126, 23, 212, 125, 819], [125, 126, 23, 212, 125, 819, 5], [125, 126, 23, 212, 125, 819, 5, 820], [821, 24], [821, 24, 23], [821, 24, 23, 213], [821, 24, 23, 213, 337], [821, 24, 23, 213, 337, 822

In [10]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

샘플의 최대 길이 : 18
[[   0    0    0 ...    0  807  330]
 [   0    0    0 ...  807  330  331]
 [   0    0    0 ...  330  331  808]
 ...
 [   0    0    0 ... 2325 2326 2327]
 [   0    0    0 ... 2326 2327 2328]
 [   0    0    0 ... 2327 2328 2329]]


In [11]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

print(sequences.shape)

(3892, 18)


In [12]:
print(X)

[[   0    0    0 ...    0    0  807]
 [   0    0    0 ...    0  807  330]
 [   0    0    0 ...  807  330  331]
 ...
 [   0    0    0 ...    0 2325 2326]
 [   0    0    0 ... 2325 2326 2327]
 [   0    0    0 ... 2326 2327 2328]]


In [13]:
print(y)

[ 330  331  808 ... 2327 2328 2329]


In [14]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### 2) 모델 설계하기
RNN 모델에 데이터를 훈련시키기

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [16]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
122/122 - 8s - loss: 7.7329 - accuracy: 0.0082 - 8s/epoch - 62ms/step
Epoch 2/200
122/122 - 5s - loss: 7.4513 - accuracy: 0.0100 - 5s/epoch - 40ms/step
Epoch 3/200
122/122 - 5s - loss: 7.3137 - accuracy: 0.0113 - 5s/epoch - 38ms/step
Epoch 4/200
122/122 - 5s - loss: 7.2065 - accuracy: 0.0123 - 5s/epoch - 38ms/step
Epoch 5/200
122/122 - 5s - loss: 7.1005 - accuracy: 0.0105 - 5s/epoch - 40ms/step
Epoch 6/200
122/122 - 5s - loss: 6.9939 - accuracy: 0.0126 - 5s/epoch - 41ms/step
Epoch 7/200
122/122 - 5s - loss: 6.8851 - accuracy: 0.0146 - 5s/epoch - 42ms/step
Epoch 8/200
122/122 - 5s - loss: 6.7755 - accuracy: 0.0203 - 5s/epoch - 40ms/step
Epoch 9/200
122/122 - 5s - loss: 6.6611 - accuracy: 0.0213 - 5s/epoch - 41ms/step
Epoch 10/200
122/122 - 5s - loss: 6.5488 - accuracy: 0.0229 - 5s/epoch - 41ms/step
Epoch 11/200
122/122 - 5s - loss: 6.4371 - accuracy: 0.0252 - 5s/epoch - 41ms/step
Epoch 12/200
122/122 - 5s - loss: 6.3259 - accuracy: 0.0293 - 5s/epoch - 42ms/step
Epoch 13/200


In [67]:
def sentence_generation(current_word, n, temperature=1.0, model=model, tokenizer=tokenizer):
    init_word = current_word
    sentence = ''

    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        
        result = model.predict(encoded, verbose=0)
        result = result / temperature
        result = np.exp(result) / np.sum(np.exp(result), axis=1)
        sampled_index = np.random.choice(len(result[0]), p=result[0])
        word = tokenizer.index_word[sampled_index]

        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence