# RNN

In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
df = pd.read_excel(r'C:\Users\GJAISCHOOL\Desktop\X_filter\Algorithm\dataset\Rnn_practice.xlsx')
df.head()

Sentence
0  이런 나에게 지루함을
1   이런 나에게 행복을
2   이런 나에게 슬픔을
3  이런 나에게 즐거움을
4  이런 나에게 무료함을

In [3]:
sentences = df['Sentence'].tolist()
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)
print(tokenizer.word_index)

단어 집합의 크기 : 105
{'이런': 1, '나에게': 2, '지루함을': 3, '행복을': 4, '슬픔을': 5, '즐거움을': 6, '무료함을': 7, '따분함을': 8, '분노를': 9, '아픔을': 10, '감격을': 11, '걱정을': 12, '괜찮음을': 13, '신기함을': 14, '신남을': 15, '쓸쓸함을': 16, '안쓰러움을': 17, '안타까움을': 18, '어이없음을': 19, '얼떨떨함을': 20, '예쁨을': 21, '용감함을': 22, '울적함을': 23, '원망을': 24, '자랑스러움을': 25, '뭉클함을': 26, '벅참을': 27, '환희를': 28, '충만함을': 29, '고마움을': 30, '유쾌함을': 31, '통쾌함을': 32, '흔쾌함을': 33, '반가움을': 34, '따뜻함을': 35, '감미로움을': 36, '포근함을': 37, '푸근함을': 38, '사랑스러움을': 39, '사랑을': 40, '훈훈함을': 41, '정겨움을': 42, '정을': 43, '뿌듯함을': 44, '산뜻함을': 45, '만족스러움을': 46, '상쾌함을': 47, '흡족함을': 48, '개운함을': 49, '후련함을': 50, '든든함을': 51, '홀가분함을': 52, '느긋함을': 53, '담담함을': 54, '친밀함을': 55, '긴장을': 56, '안심을': 57, '가벼움을': 58, '평화로움을': 59, '누그러움을': 60, '고요함을': 61, '여유로움을': 62, '진정을': 63, '잠잠함을': 64, '평온함을': 65, '흥미로움을': 66, '매혹을': 67, '재미를': 68, '끌리는': 69, '짜릿함을': 70, '신나는': 71, '용기를': 72, '기력이': 73, '넘치는': 74, '기운을': 75, '당당함을': 76, '살아있음을': 77, '생기를': 78, '원기를': 79, '자신감을': 80, '두근거림을': 81, '기대를': 82, '들뜸을': 83, '희망을': 84,

In [4]:
sequences = list()
for line in sentences:
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[: i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수 : %d' % len(sequences))
print(sequences)

학습에 사용할 샘플의 개수 : 202
[[1, 2], [1, 2, 3], [1, 2], [1, 2, 4], [1, 2], [1, 2, 5], [1, 2], [1, 2, 6], [1, 2], [1, 2, 7], [1, 2], [1, 2, 8], [1, 2], [1, 2, 9], [1, 2], [1, 2, 10], [1, 2], [1, 2, 11], [1, 2], [1, 2, 12], [1, 2], [1, 2, 13], [1, 2], [1, 2, 14], [1, 2], [1, 2, 15], [1, 2], [1, 2, 16], [1, 2], [1, 2, 17], [1, 2], [1, 2, 18], [1, 2], [1, 2, 19], [1, 2], [1, 2, 20], [1, 2], [1, 2, 21], [1, 2], [1, 2, 22], [1, 2], [1, 2, 23], [1, 2], [1, 2, 24], [1, 2], [1, 2, 25], [1, 2], [1, 2, 26], [1, 2], [1, 2, 27], [1, 2], [1, 2, 28], [1, 2], [1, 2, 29], [1, 2], [1, 2, 30], [1, 2], [1, 2, 31], [1, 2], [1, 2, 32], [1, 2], [1, 2, 33], [1, 2], [1, 2, 34], [1, 2], [1, 2, 35], [1, 2], [1, 2, 36], [1, 2], [1, 2, 37], [1, 2], [1, 2, 38], [1, 2], [1, 2, 39], [1, 2], [1, 2, 40], [1, 2], [1, 2, 41], [1, 2], [1, 2, 42], [1, 2], [1, 2, 43], [1, 2], [1, 2, 44], [1, 2], [1, 2, 45], [1, 2], [1, 2, 46], [1, 2], [1, 2, 47], [1, 2], [1, 2, 48], [1, 2], [1, 2, 49], [1, 2], [1, 2, 50], [1, 2], [1, 2, 51], [1, 2

In [5]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

샘플의 최대 길이 : 4
[[  0   0   1   2]
 [  0   1   2   3]
 [  0   0   1   2]
 [  0   1   2   4]
 [  0   0   1   2]
 [  0   1   2   5]
 [  0   0   1   2]
 [  0   1   2   6]
 [  0   0   1   2]
 [  0   1   2   7]
 [  0   0   1   2]
 [  0   1   2   8]
 [  0   0   1   2]
 [  0   1   2   9]
 [  0   0   1   2]
 [  0   1   2  10]
 [  0   0   1   2]
 [  0   1   2  11]
 [  0   0   1   2]
 [  0   1   2  12]
 [  0   0   1   2]
 [  0   1   2  13]
 [  0   0   1   2]
 [  0   1   2  14]
 [  0   0   1   2]
 [  0   1   2  15]
 [  0   0   1   2]
 [  0   1   2  16]
 [  0   0   1   2]
 [  0   1   2  17]
 [  0   0   1   2]
 [  0   1   2  18]
 [  0   0   1   2]
 [  0   1   2  19]
 [  0   0   1   2]
 [  0   1   2  20]
 [  0   0   1   2]
 [  0   1   2  21]
 [  0   0   1   2]
 [  0   1   2  22]
 [  0   0   1   2]
 [  0   1   2  23]
 [  0   0   1   2]
 [  0   1   2  24]
 [  0   0   1   2]
 [  0   1   2  25]
 [  0   0   1   2]
 [  0   1   2  26]
 [  0   0   1   2]
 [  0   1   2  27]
 [  0   0   1   2]
 [  0   1   2  28

In [6]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

print(sequences.shape)

(202, 4)


In [7]:
print(X)

[[ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0  1  2]
 [ 0  0  1]
 [ 0

In [8]:
print(y)

[  2   3   2   4   2   5   2   6   2   7   2   8   2   9   2  10   2  11
   2  12   2  13   2  14   2  15   2  16   2  17   2  18   2  19   2  20
   2  21   2  22   2  23   2  24   2  25   2  26   2  27   2  28   2  29
   2  30   2  31   2  32   2  33   2  34   2  35   2  36   2  37   2  38
   2  39   2  40   2  41   2  42   2  43   2  44   2  45   2  46   2  47
   2  48   2  49   2  50   2  51   2  52   2  53   2  54   2  55   2  56
   2  57   2  58   2  59   2  60   2  61   2  62   2  63   2  64   2  65
   2  66   2  67   2  68   2  69   2  70   2  71   2  72   2  73  74   2
  75   2  76   2  77   2  78   2  79   2  80   2  81   2  82   2  83   2
  84   2  85   2  86   2  87   2  88   2  89   2  90   2  91   2  92   2
  93  94   2  95   2  96   2  97   2  98   2  99   2 100   2 101   2 102
   2 103   2 104]


In [9]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### 2) 모델 설계하기
RNN 모델에 데이터를 훈련시키기

In [10]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
import tensorflow as tf
import os

# 스레딩 설정 변경
os.environ["TF_NUM_INTEROP_THREADS"] = "1"

# TensorFlow 초기화
tf.compat.v1.Session()

# 변경된 설정 확인
print(tf.config.threading.get_inter_op_parallelism_threads())


0


In [12]:
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200


InternalError: Graph execution error:

Detected at node 'sequential/simple_rnn/while/simple_rnn_cell/MatMul_1' defined at (most recent call last):
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\traitlets\config\application.py", line 1053, in launch_instance
      app.start()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelapp.py", line 737, in start
      self.io_loop.start()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 524, in dispatch_queue
      await self.process_one()
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 513, in process_one
      await dispatch(*args)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 418, in dispatch_shell
      await result
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\kernelbase.py", line 758, in execute_request
      reply_content = await reply_content
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\ipkernel.py", line 426, in do_execute
      res = shell.run_cell(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
      result = self._run_cell(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
      result = runner(coro)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\GJAISCHOOL\AppData\Local\Temp\ipykernel_16612\827228583.py", line 1, in <module>
      model.fit(X, y, epochs=200, verbose=2)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 889, in train_step
      y_pred = self(x, training=True)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\sequential.py", line 374, in call
      return super(Sequential, self).call(inputs, training=training, mask=mask)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\functional.py", line 458, in call
      return self._run_internal_graph(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 515, in __call__
      return super(RNN, self).__call__(inputs, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\simple_rnn.py", line 391, in call
      return super(SimpleRNN, self).call(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 652, in call
      last_output, outputs, states = backend.rnn(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 4776, in rnn
      final_outputs = tf.compat.v1.while_loop(
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 4759, in _step
      output, new_states = step_function(current_input,
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\base_rnn.py", line 648, in step
      output, new_states = cell_call_fn(inputs, states, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\layers\rnn\simple_rnn.py", line 194, in call
      output = h + backend.dot(prev_output, self.recurrent_kernel)
    File "c:\Users\GJAISCHOOL\.conda\envs\nv38\lib\site-packages\keras\backend.py", line 2223, in dot
      out = tf.matmul(x, y)
Node: 'sequential/simple_rnn/while/simple_rnn_cell/MatMul_1'
Attempting to perform BLAS operation using StreamExecutor without BLAS support
	 [[{{node sequential/simple_rnn/while/simple_rnn_cell/MatMul_1}}]] [Op:__inference_train_function_1512]

In [ ]:
def sentence_generation(current_word, n, temperature=1.0, model=model, tokenizer=tokenizer):
    init_word = current_word
    sentence = ''

    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        
        result = model.predict(encoded, verbose=0)
        result = result / temperature
        result = np.exp(result) / np.sum(np.exp(result), axis=1)
        sampled_index = np.random.choice(len(result[0]), p=result[0])
        word = tokenizer.index_word[sampled_index]

        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [ ]:
sentence_generation("마법", 3)